### ISSUE TITLE
Umbrella: Delete blogs

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#321]
Today we have decided that the blog feature of serlo.org shall be deleted because we haven't used it since 2 years:

- [ ] Move current blog articles to https://de.serlo.org/community/blog-beitr%C3%A4ge-%28archiv%29
- [ ] Delete blog feature from the codebase
- [ ] Delete blog entries from the database
