### ISSUE TITLE
Umbrella: Reportet Bugs in edtr.io

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#346]
This issue contains reported bugs which need to be checked by me.

**Comment by kulla** [comment]
Bug 1: Beim Klick auf die Schaltfläche "duplizieren" hat sich das Programm aufgehangen. Das heißt, immer wenn ich nach dem klicken von "duplizieren" in einem Eingabefeld etwas verändert und dann das Feld verlassen habe, wurde das Feld auf den Stand vor der Änderung zurückgesetzt. Es waren also keine Änderungen mehr möglich.

Bug 2: Ist etwas umständlicher zu beschreiben. Ich hatte eine Liste mit Punkten editiert und dort neue Punkte eingefügt (ohne auf die "duplizieren"-Fläche zu klicken). Ab einem gewissen Zeitpunkt ließen sich wie bei Bug 1 keine Änderungen mehr vornehmen. Ich habe dann die Änderungen vorläufig gespeichert (um nicht die gesamte bisherige Arbeit zu verlieren) und erneut begonnen, den Artikel zu bearbeiten. Danach lief das Programm wieder ohne Probleme.

**Comment by yolo-bird** [comment]
- [ ] Semantisches Content PlugIn: Aufgaben
Hier felht ein Leerzeichen zwischen Doppelpunkt und verlinktem Wort
![Screenshot_2020-04-03 87545](https://user-images.githubusercontent.com/46370375/78344817-36ec6a00-759d-11ea-8935-e39c3b52fc9b.png)

- [ ] Lange Spoilertitel werden im Editor nicht komplett angezeigt
![Screenshot_2020-04-03 Serlo – Die freie Lernplattform](https://user-images.githubusercontent.com/46370375/78344986-7915ab80-759d-11ea-9511-1cdc735faaf4.png)

- [ ] In der Revieweransicht. Bei der Injection einer Aufgabe in einem Spoiler wird die Lösung nicht aufgeklappt.
https://de.serlo.org/entity/repository/compare/143547/159233
![Screenshot_2020-04-03 Eine Multiple-Choice-Aufgabe erstellen – 2020-04-01 17 04 14+0200 von clavicina](https://user-images.githubusercontent.com/46370375/78345661-36080800-759e-11ea-8f51-59e7c31f8a63.png)

- [ ] Wenn man beim Hochladen eines Videos vergisst den Titel anzugeben, kann man nicht abspeichern. Da Titel ein Pflichtfeld ist, würde ich mir ein Fehlermeldung wünsche a la "Feld Titel ist nicht ausgefüllt"

**Comment by yolo-bird** [comment]
- [ ] Automatisiertes Hinzufügen der linken Klammer bei dieseer Formel: 

![Screenshot_2020-04-08 Serlo – Die freie Lernplattform](https://user-images.githubusercontent.com/46370375/78762078-b5714f00-7983-11ea-8db1-5c984d50369e.png)
Zugehörige Aufgabe: serlo.org/138662

- [ ] Wenn man bei Verlinkungen auf die Serlo-ID den "/" weglässt, kommt man dierekt in die Bearbeitung des Zugehlrigen Inhalts mit der SerloID

**Comment by inyono** [comment]
Can we please create individual issues for that? Otherwise, it's hard to prioritize or discuss.

**Comment by yolo-bird** [comment]
Done :-)
