### ISSUE TITLE
☂️ Umbrella Issue: Follow Ups of new Alias System

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#557]
- [x] fixtures at api.serlo.org need to be updated
- [ ] API: `/api/alias/user/profile/...` was updated -> Do we need canges there (for example in the contract tests?)
- [x] URLs für static-pages
